# Generated by Django 3.2 on 2021-07-09 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 15, 2, 55, 623193)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 15, 2, 55, 608234)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementapp.department'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementapp.doctor'),
        ),
    ]
