# Generated by Django 3.2 on 2021-07-09 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0002_auto_20210709_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 19, 26, 221722)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 19, 26, 203770)),
        ),
    ]
