# Generated by Django 3.2 on 2021-07-09 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0003_auto_20210709_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 29, 42, 55261)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 29, 42, 41347)),
        ),
    ]
