# Generated by Django 3.2 on 2021-07-09 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0004_auto_20210709_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='advance_payment',
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 58, 57, 338144)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 16, 58, 57, 324180)),
        ),
    ]
