# Generated by Django 3.2 on 2021-07-09 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0006_auto_20210709_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermedicine',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 20, 20, 54, 628362)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 20, 20, 54, 606419)),
        ),
    ]
